version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile # The backend Dockerfile
    container_name: backend
    ports:
      - '5000:5000' # Exposing port 5000 to the host
    networks:
      - proshop-network
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGO_URI: mongodb://mongo:27017 # Change this to match the service name below
      JWT_SECRET: 'abc123'
      PAYPAL_CLIENT_ID: your paypal client id

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile # The frontend Dockerfile
    container_name: frontend
    ports:
      - '3000:80' # Mapping port 3000 (host) to port 80 (Nginx inside container)
    depends_on:
      - backend
    networks:
      - proshop-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    networks:
      - proshop-network

  seed:
    build:
      context: .
      dockerfile: Dockerfile # Reuse the backend Dockerfile
    container_name: seed
    depends_on:
      - mongo
    networks:
      - proshop-network
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://mongo:27017
    command: ["npm", "run", "data:import"] # Run the seed script

networks:
  proshop-network:
    driver: bridge
    name: proshop-network
